// CONTRACTOR TYPES
export const FETCH_CONTRACTORS_REQUEST = 'FETCH_CONTRACTORS_REQUEST';
export const FETCH_CONTRACTORS_SUCCESS = 'FETCH_CONTRACTORS_SUCCESS';
export const FETCH_CONTRACTORS_FAILURE = 'FETCH_CONTRACTORS_FAILURE';

export const ADD_CONTRACTOR_REQUEST = 'ADD_CONTRACTOR_REQUEST';
export const ADD_CONTRACTOR_SUCCESS = 'ADD_CONTRACTOR_SUCCESS';
export const ADD_CONTRACTOR_FAILURE = 'ADD_CONTRACTOR_FAILURE';

export const UPDATE_CONTRACTOR_REQUEST = 'UPDATE_CONTRACTOR_REQUEST';
export const UPDATE_CONTRACTOR_SUCCESS = 'UPDATE_CONTRACTOR_SUCCESS';
export const UPDATE_CONTRACTOR_FAILURE = 'UPDATE_CONTRACTOR_FAILURE';

export const DELETE_CONTRACTOR_REQUEST = 'DELETE_CONTRACTOR_REQUEST';
export const DELETE_CONTRACTOR_SUCCESS = 'DELETE_CONTRACTOR_SUCCESS';
export const DELETE_CONTRACTOR_FAILURE = 'DELETE_CONTRACTOR_FAILURE';

// TENANT TYPES
export const FETCH_TENANTS_REQUEST = 'FETCH_TENANTS_REQUEST';
export const FETCH_TENANTS_SUCCESS = 'FETCH_TENANTS_SUCCESS';
export const FETCH_TENANTS_FAILURE = 'FETCH_TENANTS_FAILURE';

export const ADD_TENANT_REQUEST = 'ADD_TENANT_REQUEST';
export const ADD_TENANT_SUCCESS = 'ADD_TENANT_SUCCESS';
export const ADD_TENANT_FAILURE = 'ADD_TENANT_FAILURE';

export const UPDATE_TENANT_REQUEST = 'UPDATE_TENANT_REQUEST';
export const UPDATE_TENANT_SUCCESS = 'UPDATE_TENANT_SUCCESS';
export const UPDATE_TENANT_FAILURE = 'UPDATE_TENANT_FAILURE';

export const DELETE_TENANT_REQUEST = 'DELETE_TENANT_REQUEST';
export const DELETE_TENANT_SUCCESS = 'DELETE_TENANT_SUCCESS';
export const DELETE_TENANT_FAILURE = 'DELETE_TENANT_FAILURE';