// CONTRACTOR TYPES
export const FETCH_CONTRACTORS_REQUEST = 'FETCH_CONTRACTORS_REQUEST';
export const FETCH_CONTRACTORS_SUCCESS = 'FETCH_CONTRACTORS_SUCCESS';
export const FETCH_CONTRACTORS_FAILURE = 'FETCH_CONTRACTORS_FAILURE';

export const UPDATE_CONTRACTOR_REQUEST = 'UPDATE_CONTRACTOR_REQUEST';
export const UPDATE_CONTRACTOR_SUCCESS = 'UPDATE_CONTRACTOR_SUCCESS';
export const UPDATE_CONTRACTOR_FAILURE = 'UPDATE_CONTRACTOR_FAILURE';



// TENANT TYPES
export const FETCH_TENANTS_REQUEST = 'FETCH_TENANTS_REQUEST';
export const FETCH_TENANTS_SUCCESS = 'FETCH_TENANTS_SUCCESS';
export const FETCH_TENANTS_FAILURE = 'FETCH_TENANTS_FAILURE';



export const UPDATE_TENANT_REQUEST = 'UPDATE_TENANT_REQUEST';
export const UPDATE_TENANT_SUCCESS = 'UPDATE_TENANT_SUCCESS';
export const UPDATE_TENANT_FAILURE = 'UPDATE_TENANT_FAILURE';
